### ISSUE TITLE
Application Failing while npm install

### ISSUE THREAD

**Issue by SevanandYadav** [jupyterhub/configurable-http-proxy#249]
The First time i installed the npm managed application it worked fine . but next time installed on the machine it shows following Error:
==========================================================================
- Installing packages...
util.js:160
    throw new  ('superCtor.prototype',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at Object.inherits (util.js:160:11)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_duplex.js:53:6)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\readable.js:16:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Tried removing loader.js but issue still persists.
Please Suggest resolution

**Comment by SevanandYadav** [comment]
Following is the dependency ,which seems to be broken :
"dependencies": {
    "@angular/animations": "~10.0.2",
    "@angular/common": "~10.0.2",
    "@angular/compiler": "~10.0.2",
    "@angular/core": "~10.0.2",
    "@angular/forms": "~10.0.2",
    "@angular/platform-browser": "~10.0.2",
    "@angular/platform-browser-dynamic": "~10.0.2",
    "@angular/router": "~10.0.2",
    "angular-google-charts": "^0.1.3",
    "bootstrap": "^4.5.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"

**Comment by consideRatio** [comment]
Hi @SevanandYadav - it seems like this issue is entirely unrelated to configurable-http-proxy from what i can tell.

I picked up that from the path of your error: 

C:\Program Files\nodejs\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib_stream_duplex.js:53:6
