### ISSUE TITLE
cannot install on ubuntu on wsl 

### ISSUE THREAD

**Issue by wuhongyewhy** [jupyterhub/configurable-http-proxy#309]
### Bug description

cannot install on ubuntu 18.04.02 LTS on wsl2 on Win10 21H1

#### Expected behaviour

Should installed ok
#### Actual behaviour

Error in installation
### How to reproduce

1.  npm install -g configurable-http-proxy
2. got errors:
npm ERR! Linux 4.19.128-microsoft-standard
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "configurable-http-proxy"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/why/npm-debug.log

### Your personal set up

 - OS:
 
 - Version(s): ubuntu 18.04.02 LTS on wsl2 on Win10 21H1
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'configurable-http-proxy' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData configurable-http-proxy
8 silly fetchDirectoryPackageData configurable-http-proxy
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly resolveWithNewModule configurable-http-proxy@4.3.3-dev.0 checking installable status
22 silly cache add args [ 'configurable-http-proxy', null ]
23 verbose cache add spec configurable-http-proxy
24 silly cache add parsed spec Result {
24 silly cache add   raw: 'configurable-http-proxy',
24 silly cache add   scope: null,
24 silly cache add   name: null,
24 silly cache add   rawSpec: 'configurable-http-proxy',
24 silly cache add   spec: '/home/why/configurable-http-proxy',
24 silly cache add   type: 'directory' }
25 verbose addLocalDirectory /home/why/.npm/configurable-http-proxy/4.3.3-dev.0/package.tgz not in flight; packing
26 info lifecycle configurable-http-proxy@4.3.3-dev.0~prepublish: configurable-http-proxy@4.3.3-dev.0
27 silly lifecycle configurable-http-proxy@4.3.3-dev.0~prepublish: no script for prepublish, continuing
28 verbose tar pack [ '/home/why/.npm/configurable-http-proxy/4.3.3-dev.0/package.tgz',
28 verbose tar pack   '/home/why/configurable-http-proxy' ]
29 verbose tarball /home/why/.npm/configurable-http-proxy/4.3.3-dev.0/package.tgz
30 verbose folder /home/why/configurable-http-proxy
31 verbose addLocalTarball adding from inside cache /home/why/.npm/configurable-http-proxy/4.3.3-dev.0/package.tgz
32 silly cache afterAdd configurable-http-proxy@4.3.3-dev.0
33 verbose afterAdd /home/why/.npm/configurable-http-proxy/4.3.3-dev.0/package/package.json not in flight; writing
34 verbose afterAdd /home/why/.npm/configurable-http-proxy/4.3.3-dev.0/package/package.json written
35 silly fetchNamedPackageData commander
36 silly mapToRegistry name commander
37 silly mapToRegistry using default registry
38 silly mapToRegistry registry https://registry.npmjs.org/
39 silly mapToRegistry uri https://registry.npmjs.org/commander
40 silly fetchNamedPackageData http-proxy
41 silly mapToRegistry name http-proxy
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/http-proxy
45 silly fetchNamedPackageData lynx
46 silly mapToRegistry name lynx
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry uri https://registry.npmjs.org/lynx
50 silly fetchNamedPackageData strftime
51 silly mapToRegistry name strftime
52 silly mapToRegistry using default registry
53 silly mapToRegistry registry https://registry.npmjs.org/
54 silly mapToRegistry uri https://registry.npmjs.org/strftime
55 silly fetchNamedPackageData winston
56 silly mapToRegistry name winston
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry uri https://registry.npmjs.org/winston
60 verbose request uri https://registry.npmjs.org/http-proxy
61 verbose request no auth needed
62 info attempt registry request try #1 at 5:26:33 PM
63 verbose request id 900fe8e002926ae4
64 verbose etag W/"8186fd9922ae04b45bd8455f8f767e5a"
65 verbose lastModified Sun, 17 May 2020 21:27:37 GMT
66 http request GET https://registry.npmjs.org/http-proxy
67 verbose request uri https://registry.npmjs.org/lynx
68 verbose request no auth needed
69 info attempt registry request try #1 at 5:26:33 PM
70 verbose etag W/"36f04d9b07b2343cd836a86d0cf0024e"
71 verbose lastModified Sun, 27 May 2018 07:12:44 GMT
72 http request GET https://registry.npmjs.org/lynx
73 verbose request uri https://registry.npmjs.org/strftime
74 verbose request no auth needed
75 info attempt registry request try #1 at 5:26:33 PM
76 verbose etag W/"9c74cbbdb5d6ef4af2d44d855457bca6"
77 verbose lastModified Sun, 27 May 2018 18:24:18 GMT
78 http request GET https://registry.npmjs.org/strftime
79 verbose request uri https://registry.npmjs.org/winston
80 verbose request no auth needed
81 info attempt registry request try #1 at 5:26:33 PM
82 verbose etag W/"b573c1bb638b94fa77cdb6e122da489e"
83 verbose lastModified Tue, 23 Jun 2020 22:31:29 GMT
84 http request GET https://registry.npmjs.org/winston
85 verbose request uri https://registry.npmjs.org/commander
86 verbose request no auth needed
87 info attempt registry request try #1 at 5:26:33 PM
88 verbose etag W/"3abc6a0addb59d19eb88313c9c18f297"
89 verbose lastModified Sun, 21 Mar 2021 21:56:19 GMT
90 http request GET https://registry.npmjs.org/commander
91 http 304 https://registry.npmjs.org/commander
92 verbose headers { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
92 verbose headers   connection: 'keep-alive',
92 verbose headers   'set-cookie':
92 verbose headers    [ '__cfduid=d15a07879bc2553daf12f627ef8c758a41619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
92 verbose headers   'cf-ray': '64670286eac835f1-LAX',
92 verbose headers   age: '6843',
92 verbose headers   'cache-control': 'public, max-age=300',
92 verbose headers   etag: '"3abc6a0addb59d19eb88313c9c18f297"',
92 verbose headers   'last-modified': 'Sun, 21 Mar 2021 21:56:19 GMT',
92 verbose headers   vary: 'Accept-Encoding',
92 verbose headers   'cf-cache-status': 'HIT',
92 verbose headers   'cf-request-id': '09b43fe855000035f1f5377000000001',
92 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
92 verbose headers   server: 'cloudflare' }
93 silly get cb [ 304,
93 silly get   { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
93 silly get     connection: 'keep-alive',
93 silly get     'set-cookie':
93 silly get      [ '__cfduid=d15a07879bc2553daf12f627ef8c758a41619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
93 silly get     'cf-ray': '64670286eac835f1-LAX',
93 silly get     age: '6843',
93 silly get     'cache-control': 'public, max-age=300',
93 silly get     etag: '"3abc6a0addb59d19eb88313c9c18f297"',
93 silly get     'last-modified': 'Sun, 21 Mar 2021 21:56:19 GMT',
93 silly get     vary: 'Accept-Encoding',
93 silly get     'cf-cache-status': 'HIT',
93 silly get     'cf-request-id': '09b43fe855000035f1f5377000000001',
93 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
93 silly get     server: 'cloudflare' } ]
94 verbose etag https://registry.npmjs.org/commander from cache
95 verbose get saving commander to /home/why/.npm/registry.npmjs.org/commander/.cache.json
96 http 304 https://registry.npmjs.org/lynx
97 verbose headers { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
97 verbose headers   connection: 'keep-alive',
97 verbose headers   'set-cookie':
97 verbose headers    [ '__cfduid=d1c410f9a775c70a6bd592d9e6d68a9e61619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
97 verbose headers   'cf-ray': '64670286ea5042bd-LAX',
97 verbose headers   age: '1178',
97 verbose headers   'cache-control': 'public, max-age=300',
97 verbose headers   etag: '"36f04d9b07b2343cd836a86d0cf0024e"',
97 verbose headers   'last-modified': 'Sun, 27 May 2018 07:12:44 GMT',
97 verbose headers   vary: 'Accept-Encoding',
97 verbose headers   'cf-cache-status': 'HIT',
97 verbose headers   'cf-request-id': '09b43fe850000042bd9d27e000000001',
97 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
97 verbose headers   server: 'cloudflare' }
98 silly get cb [ 304,
98 silly get   { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
98 silly get     connection: 'keep-alive',
98 silly get     'set-cookie':
98 silly get      [ '__cfduid=d1c410f9a775c70a6bd592d9e6d68a9e61619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
98 silly get     'cf-ray': '64670286ea5042bd-LAX',
98 silly get     age: '1178',
98 silly get     'cache-control': 'public, max-age=300',
98 silly get     etag: '"36f04d9b07b2343cd836a86d0cf0024e"',
98 silly get     'last-modified': 'Sun, 27 May 2018 07:12:44 GMT',
98 silly get     vary: 'Accept-Encoding',
98 silly get     'cf-cache-status': 'HIT',
98 silly get     'cf-request-id': '09b43fe850000042bd9d27e000000001',
98 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
98 silly get     server: 'cloudflare' } ]
99 verbose etag https://registry.npmjs.org/lynx from cache
100 verbose get saving lynx to /home/why/.npm/registry.npmjs.org/lynx/.cache.json
101 http 304 https://registry.npmjs.org/strftime
102 verbose headers { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
102 verbose headers   connection: 'keep-alive',
102 verbose headers   'set-cookie':
102 verbose headers    [ '__cfduid=d0246c1175b343e807985e9df709982941619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
102 verbose headers   'cf-ray': '64670286fa743689-LAX',
102 verbose headers   age: '201',
102 verbose headers   'cache-control': 'public, max-age=300',
102 verbose headers   etag: '"9c74cbbdb5d6ef4af2d44d855457bca6"',
102 verbose headers   'last-modified': 'Sun, 27 May 2018 18:24:18 GMT',
102 verbose headers   vary: 'Accept-Encoding',
102 verbose headers   'cf-cache-status': 'HIT',
102 verbose headers   'cf-request-id': '09b43fe85a00003689f98b9000000001',
102 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
102 verbose headers   server: 'cloudflare' }
103 silly get cb [ 304,
103 silly get   { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
103 silly get     connection: 'keep-alive',
103 silly get     'set-cookie':
103 silly get      [ '__cfduid=d0246c1175b343e807985e9df709982941619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
103 silly get     'cf-ray': '64670286fa743689-LAX',
103 silly get     age: '201',
103 silly get     'cache-control': 'public, max-age=300',
103 silly get     etag: '"9c74cbbdb5d6ef4af2d44d855457bca6"',
103 silly get     'last-modified': 'Sun, 27 May 2018 18:24:18 GMT',
103 silly get     vary: 'Accept-Encoding',
103 silly get     'cf-cache-status': 'HIT',
103 silly get     'cf-request-id': '09b43fe85a00003689f98b9000000001',
103 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
103 silly get     server: 'cloudflare' } ]
104 verbose etag https://registry.npmjs.org/strftime from cache
105 verbose get saving strftime to /home/why/.npm/registry.npmjs.org/strftime/.cache.json
106 http 304 https://registry.npmjs.org/http-proxy
107 verbose headers { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
107 verbose headers   connection: 'keep-alive',
107 verbose headers   'set-cookie':
107 verbose headers    [ '__cfduid=d0a45cdf8d999128672a96f134de77f491619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
107 verbose headers   'cf-ray': '64670286e8c0e502-LAX',
107 verbose headers   age: '860',
107 verbose headers   'cache-control': 'public, max-age=300',
107 verbose headers   etag: '"8186fd9922ae04b45bd8455f8f767e5a"',
107 verbose headers   'last-modified': 'Sun, 17 May 2020 21:27:37 GMT',
107 verbose headers   vary: 'Accept-Encoding',
107 verbose headers   'cf-cache-status': 'HIT',
107 verbose headers   'cf-request-id': '09b43fe8510000e5022d06c000000001',
107 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
107 verbose headers   server: 'cloudflare' }
108 silly get cb [ 304,
108 silly get   { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
108 silly get     connection: 'keep-alive',
108 silly get     'set-cookie':
108 silly get      [ '__cfduid=d0a45cdf8d999128672a96f134de77f491619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
108 silly get     'cf-ray': '64670286e8c0e502-LAX',
108 silly get     age: '860',
108 silly get     'cache-control': 'public, max-age=300',
108 silly get     etag: '"8186fd9922ae04b45bd8455f8f767e5a"',
108 silly get     'last-modified': 'Sun, 17 May 2020 21:27:37 GMT',
108 silly get     vary: 'Accept-Encoding',
108 silly get     'cf-cache-status': 'HIT',
108 silly get     'cf-request-id': '09b43fe8510000e5022d06c000000001',
108 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
108 silly get     server: 'cloudflare' } ]
109 verbose etag https://registry.npmjs.org/http-proxy from cache
110 verbose get saving http-proxy to /home/why/.npm/registry.npmjs.org/http-proxy/.cache.json
111 http 304 https://registry.npmjs.org/winston
112 verbose headers { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
112 verbose headers   connection: 'keep-alive',
112 verbose headers   'set-cookie':
112 verbose headers    [ '__cfduid=d75c5a877b92ed1c3d78952363cacd6e71619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
112 verbose headers   'cf-ray': '64670286ff1ed386-LAX',
112 verbose headers   age: '6650',
112 verbose headers   'cache-control': 'public, max-age=300',
112 verbose headers   etag: '"b573c1bb638b94fa77cdb6e122da489e"',
112 verbose headers   'last-modified': 'Tue, 23 Jun 2020 22:31:29 GMT',
112 verbose headers   vary: 'Accept-Encoding',
112 verbose headers   'cf-cache-status': 'HIT',
112 verbose headers   'cf-request-id': '09b43fe85a0000d3867e280000000001',
112 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
112 verbose headers   server: 'cloudflare' }
113 silly get cb [ 304,
113 silly get   { date: 'Tue, 27 Apr 2021 09:26:32 GMT',
113 silly get     connection: 'keep-alive',
113 silly get     'set-cookie':
113 silly get      [ '__cfduid=d75c5a877b92ed1c3d78952363cacd6e71619515592; expires=Thu, 27-May-21 09:26:32 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
113 silly get     'cf-ray': '64670286ff1ed386-LAX',
113 silly get     age: '6650',
113 silly get     'cache-control': 'public, max-age=300',
113 silly get     etag: '"b573c1bb638b94fa77cdb6e122da489e"',
113 silly get     'last-modified': 'Tue, 23 Jun 2020 22:31:29 GMT',
113 silly get     vary: 'Accept-Encoding',
113 silly get     'cf-cache-status': 'HIT',
113 silly get     'cf-request-id': '09b43fe85a0000d3867e280000000001',
113 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
113 silly get     server: 'cloudflare' } ]
114 verbose etag https://registry.npmjs.org/winston from cache
115 verbose get saving winston to /home/why/.npm/registry.npmjs.org/winston/.cache.json
116 verbose stack Error: Missing required argument #1
116 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
116 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
116 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
116 verbose stack     at /usr/share/npm/lib/install/deps.js:457:7
116 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
116 verbose stack     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
116 verbose stack     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
116 verbose stack     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
116 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
116 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
117 verbose cwd /home/why
118 error Linux 4.19.128-microsoft-standard
119 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "configurable-http-proxy"
120 error node v8.10.0
121 error npm  v3.5.2
122 error code EMISSINGARG
123 error typeerror Error: Missing required argument #1
123 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
123 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
123 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
123 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
123 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
123 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
123 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
123 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
123 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
123 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
124 error typeerror This is an error with npm itself. Please report this error at:
124 error typeerror     <http://github.com/npm/npm/issues>
125 verbose exit [ 1, true ]

```
</details>

**Comment by wuhongyewhy** [comment]
I solved myself. The default nodejs and npm are too old for ubuntu 18.04.
Updating nodejs and npm can solve this problem.
