### ISSUE TITLE
Missing PFX or certificate + private key for SSL config

### ISSUE THREAD

**Issue by stasov** [jupyterhub/configurable-http-proxy#66]
I'm trying to set up the proxy with an SSL cert.
I'm generating the cert and the key with the following command:
`openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem`

The try run the proxy with the following commands:

`configurable-http-proxy --ssl-cert=cert.pem --log-level=debug --port=443 --default-target=http://1.1.1.1`
`configurable-http-proxy --ssl-key=key.pem --log-level=debug --port=443 --default-target=http://1.1.1.1`

I keep getting this error:
```
tls.js:1125
    throw new Error('Missing PFX or certificate + private key.');
          ^
Error: Missing PFX or certificate + private key.
    at Server (tls.js:1125:11)
    at new Server (https.js:35:14)
    at Object.exports.createServer (https.js:54:10)
    at new ConfigurableProxy (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:176:35)
    at Object.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:183:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

The proxy works well without the SSL bit.
Thank you for the help.

**Comment by minrk** [comment]
You generally want both the key and cert args, unless your cert file bundles the key:

    configurable-http-proxy --ssl-key=key.pem --ssl-cert=cert.pem ...

What version of CHP and node?

**Comment by stasov** [comment]
CHP version : 1.2.0
node version : v0.10.42

Just tried both:
`configurable-http-proxy --ssl-cert=cert.pem --ssl-key=key.pem --log-level=debug --port=443 --default-target=http://1.1.1.1`

I'm getting a different error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Object.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:191:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
I'm amazed by the response time! Thank you

**Comment by minrk** [comment]
Only root is allowed to listen on low ports by default. You can either run CHP with `sudo`, or give node explicit permission to listen on low ports:

    sudo setcap 'cap_net_bind_service=+ep' `which node`

[more info](https://gist.github.com/firstdoit/6389682)

**Comment by stasov** [comment]
Provided both cert and key to CHP and ran with sudo. Worked like a charm! Many thanks!

**Comment by minrk** [comment]
Great!
