### ISSUE TITLE
Cannot delete child route after deleting parent route

### ISSUE THREAD

**Issue by invisibleroads** [jupyterhub/configurable-http-proxy#92]
Thanks for making this proxy!

We are finding that deleting /x before deleting /x/y causes an error.

```
import requests
requests.post('http://localhost:8080/api/routes/x', json={'target': 'http://localhost:5000'})
requests.post('http://localhost:8080/api/routes/x/y', json={'target': 'http://localhost:5001'})
requests.delete('http://localhost:8080/api/routes/x')
requests.delete('http://localhost:8080/api/routes/x/y')

20:01:59.255 - error: [ConfigProxy] Error in handler for DELETE /api/routes/x/y:  TypeError: Cannot read property 'remove' of undefined
    at URLTrie.remove (/usr/lib/node_modules/configurable-http-proxy/lib/trie.js:83:10)
    at ConfigurableProxy.remove_route (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:203:19)
    at ConfigurableProxy.delete_routes (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:265:14)
    at ConfigurableProxy.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:76:27)
    at Function.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:26:16)
    at ConfigurableProxy.handle_api_request (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:441:21)
    at Server.<anonymous> (/usr/lib/node_modules/configurable-http-proxy/lib/configproxy.js:154:32)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
```

However, deleting /x/y before deleting /x works as expected.

```
import requests
requests.post('http://localhost:8080/api/routes/x', json={'target': 'http://localhost:5000'})
requests.post('http://localhost:8080/api/routes/x/y', json={'target': 'http://localhost:5001'})
requests.delete('http://localhost:8080/api/routes/x/y')
requests.delete('http://localhost:8080/api/routes/x')
```

**Comment by minrk** [comment]
Good catch! #93 should fix it, I think.

**Comment by invisibleroads** [comment]
Thanks!
